import os


MAX_DAILY_ARTICLES = int(os.getenv("MAX_DAILY_ARTICLES", "30"))
MAX_ENTRIES_PER_SOURCE = int(os.getenv("MAX_ENTRIES_PER_SOURCE", "10"))
MIN_RELEVANCE_SCORE = int(os.getenv("MIN_RELEVANCE_SCORE", "60"))

CATEGORIES = [
    "AI工具",
    "模型發布",
    "研究論文",
    "開源專案",
    "產業動態",
    "投資併購",
    "政策法規",
    "AI基礎設施",
    "AI Agent / Agentic Workflow",
    "教學資源",
    "其他AI趨勢",
]

ENTITY_TYPES = [
    "tool",
    "company",
    "model",
    "framework",
    "product",
    "other",
]

TREND_SCORE_WEIGHTS = {
    "relevance": 0.35,
    "importance": 0.35,
    "source": 10,
    "entity": 4,
    "recency": 5,
}

AI_KEYWORDS = [
    "ai",
    "artificial intelligence",
    "agent",
    "agents",
    "chatgpt",
    "claude",
    "claude code",
    "gemini",
    "llm",
    "large language model",
    "openai",
    "anthropic",
    "deepmind",
    "hugging face",
    "machine learning",
    "ml",
    "neural",
    "model",
    "inference",
    "rag",
    "agentic",
    "ai agent",
    "ai agents",
    "multi-agent",
    "tool use",
    "function calling",
    "workflow automation",
    "model context protocol",
    "mcp",
    "langchain",
    "langgraph",
    "llamaindex",
    "crewai",
    "autogen",
    "semantic kernel",
    "ai sdk",
    "computer use",
    "browser use",
    "agent workflow",
    "agent framework",
    "vector database",
    "copilot",
    "cursor",
    "coding agent",
    "ai coding assistant",
    "developer agent",
    "terminal agent",
    "code generation",
    "code assistant",
    "coding assistant",
    "programming assistant",
    "software engineering agent",
    "dev tool",
    "developer tool",
    "vibe coding",
    "代理",
    "智能體",
    "多代理",
    "工具調用",
    "函式呼叫",
    "工作流",
    "生成式",
    "人工智慧",
    "機器學習",
    "模型",
    "推論",
]

DEFAULT_SOURCE_WEIGHT = 1.0
