import os


MAX_DAILY_ARTICLES = int(os.getenv("MAX_DAILY_ARTICLES", "0"))
MAX_ENTRIES_PER_SOURCE = int(os.getenv("MAX_ENTRIES_PER_SOURCE", "30"))
MIN_RELEVANCE_SCORE = int(os.getenv("MIN_RELEVANCE_SCORE", "60"))

CATEGORIES = [
    "AI 工具與應用",
    "AI Agent 與開發",
    "AI 模型與研究",
    "AI 產業與治理",
    "開源專案",
    "研究論文",
    "產業新聞",
    "其他AI趨勢",
]

TREND_SCORE_WEIGHTS = {
    "importance": 0.9,
    "source": 10,
}

AI_KEYWORDS = [
    "ai",
    "artificial intelligence",
    "agent",
    "agents",
    "chatgpt",
    "claude",
    "claude code",
    "gemini",
    "llm",
    "large language model",
    "openai",
    "anthropic",
    "deepmind",
    "hugging face",
    "machine learning",
    "ml",
    "neural",
    "model",
    "inference",
    "rag",
    "agentic",
    "ai agent",
    "ai agents",
    "multi-agent",
    "tool use",
    "function calling",
    "workflow automation",
    "model context protocol",
    "mcp",
    "langchain",
    "langgraph",
    "llamaindex",
    "crewai",
    "autogen",
    "semantic kernel",
    "ai sdk",
    "computer use",
    "browser use",
    "agent workflow",
    "agent framework",
    "vector database",
    "copilot",
    "cursor",
    "coding agent",
    "ai coding assistant",
    "developer agent",
    "terminal agent",
    "code generation",
    "code assistant",
    "coding assistant",
    "programming assistant",
    "software engineering agent",
    "dev tool",
    "developer tool",
    "vibe coding",
    "代理",
    "智能體",
    "多代理",
    "工具調用",
    "函式呼叫",
    "工作流",
    "生成式",
    "人工智慧",
    "機器學習",
    "模型",
    "推論",
]

DEFAULT_SOURCE_WEIGHT = 1.0
